services:
  # api:
  #   image: bank.presentation
  #   build:
  #     context: .
  #     dockerfile: Bank.presentation/Dockerfile
  #   ports:
  #     - "5000:8080"
  #     - "5001:8081"

  database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    #    or if there is other version like 22
    #    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local